### ISSUE TITLE
pickle error on model save

### ISSUE THREAD

**Issue by dhetting** [NREL/phygnn#16]
**Bug Description**
Can't save model

**Full Traceback**
```Traceback (most recent call last):
  File "/home/dhetting/src/mlclouds/mlclouds/scripts/train.py", line 51, in <module>
    tt.trainer.model.save_model(model_fpath)
  File "/home/dhetting/src/phygnn/phygnn/model_interfaces/phygnn_model.py", line 217, in save_model
    self.model.save(path)
  File "/home/dhetting/src/phygnn/phygnn/phygnn.py", line 812, in save
    pickle.dump(model_params, f)
AttributeError: Can't pickle local object 'make_gradient_clipnorm_fn.<locals>.<lambda>'
```
**Code Sample**
```python
tt = TrainTest(files, config=config, test_fraction=test_fraction,
                   stats_file=stats_file)

tt.trainer.model.save_model(model_fpath)

```

**Comment by MRossol** [comment]
@dhetting Lambda functions aren't pickle-able... Did you add a lambda function?

**Comment by dhetting** [comment]
No, I didn't add anything to phygnn. Started failing after pulling the latest master last week.

**Comment by grantbuster** [comment]
What model are you saving? Is this for the mlclouds project? If so, i suspect env issues since you've been having those in spades.... Another thing you can do to test is clone the phygnn repo, install an phygnn env, and run the pytests.

**Comment by dhetting** [comment]
Yea, for mlclouds. The phygnn tests fail, too (and for mlclouds). This is all in a new environment. 

![image](https://user-images.githubusercontent.com/89405/103560467-0fe8fe80-4e75-11eb-93a7-dffc45f98485.png)

**Comment by mikebannis** [comment]
I'm going to see if I can reproduce this.

**Comment by mikebannis** [comment]
Just pulled master on phygnn and the tests are working for me. I'm using tensorflow version 2.1.0.

**Comment by dhetting** [comment]
python 3.7.9 and tensorflow 2.4.0

**Comment by dhetting** [comment]
TF 2.1 is pretty old now isn't it? Pip wont even install it

**Comment by mikebannis** [comment]
Upgraded to TF 2.4.0. I'm now getting `         AttributeError: Can't pickle local object 'make_gradient_clipnorm_fn.<locals>.<lambda>'`. Something broke with the new version of TF

**Comment by MRossol** [comment]
Got to love open source software. @mikebannis  have you checked the TF issues to see if this has been reported? If so we should pin the last stable version of TF until they fix it

**Comment by grantbuster** [comment]
If anyone has time it would be worth seeing which object in the `model_params` cannot be pickled (phygnn.py, line 812). There might be an easy workaround.

**Comment by grantbuster** [comment]
Actually I can do this now.

**Comment by mikebannis** [comment]
FWIW TF 2.3.0 works fine.

**Comment by grantbuster** [comment]
Fixed in https://github.com/NREL/phygnn/pull/17. The issue is that the keras optimizer classes can no longer be pickled. Fortunately, the optimizer classes have handy `get_config()` and `from_config()` methods that use simple flat dictionaries.

**Comment by dhetting** [comment]
thanks grant, worked on my end, too
