### ISSUE TITLE
Need conv layers with more padding options

### ISSUE THREAD

**Issue by grantbuster** [NREL/phygnn#27]
**Why this feature is necessary:**
Mirror padding was used in the original super res model. 

**A possible solution is:**
Maybe do a [custom layer](https://github.com/NREL/phygnn/blob/gb/refactor/phygnn/layers/custom_layers.py) that either wraps the 2D/3D conv layer and adds the [tf.pad()](https://www.tensorflow.org/api_docs/python/tf/pad) function or do a standalone pad layer that implements tf.pad() by itself. The latter is probably more flexible. 

**Charge code**
WFED 11556 03.01.03

**Urgency / Timeframe**
In the next month

**Comment by bnb32** [comment]
added a test_padding_layers test which is just the skip_connections test with padding on the input. not sure if this the sort of integration you had in mind.
